name = "Create and Magic"
author = "Liam Fryar/Jonah Despain"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0405fbf777128b818fc9f722a1e0ad37feadf076d2c900bcfb7e67e14bc59b5e"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
