name = "Create and Magic"
author = "Liam Fryar/Jonah Despain"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e718e01ba92e2e5aa913caa846a95fa59c02d7d4c3210c835f152ec9a292a863"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
