name = "Create and Magic"
author = "Liam Fryar/Jonah Despain"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd5880875406ee989ad92be38a7935ab2bb6d04c60e4f2eb22718d780debffc0"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
